website/blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('post/<slug:slug>', views.post, name="post"),
    path('category/<slug:slug>/', views.category, name="category"),
    path('search/', views.search, name="search"),
    path('create/', views.PostCreateView.as_view(), name="create"),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='blog_login'),
    path('logout/', views.custom_logout_view, name='blog_logout')
]

website/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove')
]

website/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail')
]

website/website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', include('helloweb.urls')),
                  path('', include('blog.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('shop/', include('shop.urls')),
                  path('cart/', include('cart.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/templates/shop/detail.html
{% extends 'blog/base.html' %}
{% load thumbnail %}
{% block main %}

<h1 class="page-header"> Product detail </h1>

<div class="card">
  <img src="{{ product.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
      <h2>{{ product.title }}</h2>
      <h2>{{ product.price }}</h2>
    <p class="card-text">{{ product.content }}</p>
      <a href="{% url 'cart:cart_add' product.id %}" class="btn btn-primary">Add to cart</a>
  </div>
</div>
{% endblock %}

website/templates/shop/list.html
{% extends 'blog/base.html' %}
{% load thumbnail %}
{% block main %}

<h1 class="page-header"> Product list </h1>
{% for product in products %}
<div class="card">
    <img src="{{product.image.url}}" class="card-img-top" alt="..." style="width: 200px;">
    <div class="card-body">
        <h5 class="card-title">{{product.title}}</h5>
        UAH {{product.price}}
        <p class="card-text">{{product.content|truncatewords:6}}</p>
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Detail</a>
    </div>
</div>

{% endfor %}

{% endblock %}